# Generated by Django 3.2.12 on 2022-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_after',
            field=models.IntegerField(default=0, verbose_name='Số dư sau khi mua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='balance_before',
            field=models.IntegerField(default=1, verbose_name='Số dư trước khi mua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.IntegerField(default=0, verbose_name='Tổng tiền'),
            preserve_default=False,
        ),
    ]
