# Generated by Django 3.2.12 on 2022-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220222_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
