# Generated by Django 3.2.12 on 2022-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_hash_customer_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salt',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
