# Generated by Django 3.2.12 on 2022-02-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220225_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Số dư'),
        ),
    ]
