# Generated by Django 3.2.12 on 2022-02-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('balance_change', models.IntegerField(default=0, verbose_name='Số tiền')),
                ('balance_after', models.IntegerField(default=0, verbose_name='Số dư sau')),
                ('balance_before', models.IntegerField(default=0, verbose_name='Số dư trước')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử',
                'verbose_name_plural': 'Lịch sử',
            },
        ),
    ]
