# Generated by Django 3.2.12 on 2022-02-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20220226_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Thời gian sử dụng (phút)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time_min',
            field=models.IntegerField(default=10, verbose_name='Sử dụng tối thiểu (phút)'),
        ),
    ]
