# Generated by Django 3.2.12 on 2022-02-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Node name')),
                ('urlApi', models.CharField(max_length=191, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'Nodes',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Type name')),
            ],
            options={
                'verbose_name': 'Node type',
                'verbose_name_plural': 'Node type',
            },
        ),
        migrations.CreateModel(
            name='Socks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=191, verbose_name='socket name')),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.node', verbose_name='Node type')),
            ],
            options={
                'verbose_name': 'Socks',
                'verbose_name_plural': 'Socks',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='nodeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.nodetype', verbose_name='Node type'),
        ),
    ]
